---
title: "An example of allocation on the frontier"
author: "Davide Carboni"
date: "30 May 2016"
output: html_document
---

Example of use of frontier.R this script takes symbols and find the efficient frontier 

```{r include=FALSE}
source("util.R")
source("frontier.R")

```

Lets build a portfolio with four securities
```{r}
symbols <- c("X","FB","MA","MSFT")
days=90

```


Simulate the portfolios, use 1250 samples 
```{r}
p <- simulatePortfolios(symbols,days,len=1250)
plot(p$sd,p$mean)
```


Show the lowest risk portfolios
```{r}
p <- p[p$mean>0,]#keep positive returns only
lowRisk <- p[order(p$sd),]#show low risk portfolio
head(lowRisk)
```

Show the highest return portfolios
```{r}

highRet <- p[order(p$mean,decreasing = T),]#show high return portfolios
head(highRet)
```

Select an expected return and find the portfolio with minimun risk
```{r}
q <- p[complete.cases(p),]
best <- bestPortfolio(q,expected = 0.0015)
best
```

So if you have 1000$ to invest this is the best breakdown
```{r}
round(1000 * best)[,-5:-6] 
```


